# Config Version (上書きしないでください)
version: 1.0.0

# バックアップする間隔(分)
interval: 60

# バックアップのモード
# zip または copy を指定してください
# zip - コピーしたバックアップをZIP圧縮する
# copy - 普通のバックアップ(コピーするだけ)
# 上2つ以外を指定すると自動でcopyになります
mode: copy